Repository rl-institut/NESP2, pull requests merged in 2020-03, with the labels that each got.

#196 style state name on bottom left of the map
  app/static/css/maps.css
Labels: design

#198 fit map height to window size
  app/static/css/maps.css
Labels: design, enhancement

#197 style sidebar logos
  app/static/css/maps.css
  app/static/js/sidebar.js
  app/templates/index.html
Labels: design

#199 Fe/sidebar fix
  app/static/css/maps.css
  app/static/js/sidebar.js
  app/templates/sidebar_checkbox.html
Labels: design

#203 Remove unused files
  app/static/data/GHI.tif
  app/static/data/points.js
  app/static/images/image004.png
  app/static/images/image005.png
  app/static/images/image010.png
  app/static/images/image011.png
  app/static/images/image014.png
  app/static/images/image015.png
  app/static/images/image016.png
  app/static/images/image017.png
  app/static/images/image018.png
  app/static/images/image019.png
  app/static/images/image020.png
  app/static/images/image021.png
  app/static/images/image022.png
  app/static/images/image023.png
  app/static/images/image024.png
  app/static/images/image025.png
  app/static/images/image026.png
  app/static/images/image027.png
  app/static/images/readme-image.png
  app/static/images/screenshot.png
  app/static/images/watermark.gif
  app/static/images/zoom-in.PNG
Labels: enhancement

#201 remove space below map on larger screens when the sidebar funnel is active
  app/static/css/maps.css
  app/templates/index.html
Labels: design

#211 set logos in one line
  app/static/css/maps.css
Labels: design

#244 Feature/financial
  app/static/css/maps.css
Labels: design

#245 change distance beween blitz logo and text to fit website
  app/static/css/maps.css
Labels: design

#247 Feature/about
  CHANGELOG.md
  app/__init__.py
  app/blueprints/__init__.py
  app/blueprints/about_map.py
  app/static/css/maps.css
  app/static/img/icons/i_info.svg
  app/templates/index.html
Labels: design

#266 Feature/legend
  CHANGELOG.md
  app/static/css/legends.css
  app/static/css/maps.css
  app/static/img/icons/i_arrow_left_g.svg
  app/static/img/icons/i_arrow_right_g.svg
  app/static/js/layers.js
  app/static/js/map.js
  app/static/js/sidebar.js
  app/templates/index.html
Labels: design
